version: "3.7"

volumes:
  database: {}

services:
  database:
    image: postgres:13.2
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
